### ISSUE TITLE
[Feature]: Use sass mixins for media breakpoints

### ISSUE THREAD

**Issue by adamalfredsson** [stiftelsen-effekt/main-site#631]
### Description

Improves readability and consistency across stylesheets. Imagining something like:

```scss
@include breakpoint(sm) {
  .box {
    background: red;
  }
}
```

https://codepen.io/tctc91/pen/ZBXPOz

What do you think?
